// See https://aka.ms/new-console-template for more information

using Newtonsoft.Json;
using PopupLib;
using TetriSH;

string[] splashes = [
    "Fun!",
    "Welcome to (s)hell",
    "So you have chosen, pain",
    "The least practical shell!",
    "...",
    "Whose idea was this?",
    "Runs on 2 'AA' batteries",
    "Is tetris copyrighted?",
    "Tetrominoes!",
    "So far not rewritten in Rust",
    "Not suitable for Windows",
    "Made with a keyboard",
    "What's next, snake as a shell?"
];
string splash = splashes[new Random().Next(splashes.Length)];
string menu = "main"; // this is probably a dumb way of handling menus but i don't give a damn honestly
string datadir = $"/home/{Environment.UserName}/.local/share/tetrish";
if (!Directory.Exists(datadir)) {
    Directory.CreateDirectory(datadir);
}
Data savedata = new(); 
if (File.Exists(Path.Join(datadir, "data.json"))) {
    string json = File.ReadAllText(Path.Join(datadir, "data.json"));
    Data? notjson = JsonConvert.DeserializeObject<Data>(json);
    if (notjson is not null)
        savedata = notjson;
} else {
    SaveData();
}

if (File.Exists(Path.Join(datadir, "commands.txt"))) {
    string[] lines = File.ReadAllLines(Path.Join(datadir, "commands.txt"));
    Console.WriteLine();
    int x = Console.CursorLeft;
    int y = Console.CursorTop;
    for (int i = 0; i < lines.Length; i++) {
        string line = lines[i];
        Console.SetCursorPosition(x, y);
        Console.WriteLine($"Loading commands... ({i}/{lines.Length})");
        string trim = line[7..];
        for (int j = 0; j < trim.Length; j += 2) {
            string pair = $"{trim[j]}{(j == trim.Length - 1 ? ' ' : trim[j + 1])}";
            TetrisEngine.cpairs.Add(pair);
        }
    }
} else {
    AutogenCMDFile:
    string a = SelectPopup.Quick("No command list found. Without it, the blocks will contain completely random characters.", [ "Ok", "What" ], title: "TetriSH", type: PopupType.Warning);
    if (a == "What") {
        Popup.Quick($"The command list contains your most used shell commands, to make executing useful commands more likely. It can be automatically generated by running 'history >> {datadir}/commands.txt', or be written manually. It will not leave the device, at any point of time.", title: "TetriSH | Command file", wrap: 64);
        goto AutogenCMDFile;
    }
    string cset = "abcdefghijklmopABCDEFGHIJKLMNOP1234567890!@#$%^&*()_+{}[]<>?\\/-=;:,.`~";
    Random r = new();
    for (int i = 0; i < 256; i++) {
        TetrisEngine.cpairs.Add($"{cset[r.Next(cset.Length)]}{cset[r.Next(cset.Length)]}");
    }
}
Console.Clear();
while (true) {
    switch (menu) {
        case "main": {
            string select = SelectPopup.Quick(splash, [ "Run", "Settings", "Stats", "Quit" ], title: "TetriSH");
            switch (select) {
                case "Run": menu = "tetris"; break;
                case "Settings": menu = "settings"; break;
                case "Quit": {
                    Console.CursorVisible = true;
                    Console.Clear();
                    Environment.Exit(0);
                    break;
                }
            }
            break;
        }
        case "settings": {
            string select = SelectPopup.Quick("Settings", ["Shell", "Back"], title: "TetriSH");
            switch (select) {
                case "Shell": {
                    savedata.Exec = TextPromptPopup.Quick($"Current: {savedata.Exec}\nThe shell executable path and arguments for running commands. {{0}} will be replaced with the line that has been cleared", placeholder: "type here", title: "TetriSH | Shell");
                    SaveData();
                    break;
                }
                case "Back": menu = "main"; break;
            }
            break;
        }
        case "tetris": {
            TetrisEngine tetris = new(32, 48);
            tetris.Run();
            menu = "main";
            break;
        }
    }
}

void SaveData() {
    string json = JsonConvert.SerializeObject(savedata);
    File.WriteAllText(Path.Join(datadir, "data.json"), json);
}

class Data {
    public Data() {
        Exec = "/bin/bash -c {0}";
    }
    public string Exec { get; set; }
}